apiVersion: v1
kind: Namespace
metadata:
  name: voting-api
  labels:
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: voting-system
    app.kubernetes.io/managed-by: helm
    layer: application
