apiVersion: v1
kind: Namespace
metadata:
  name: voting-frontend
  labels:
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: voting-system
    app.kubernetes.io/managed-by: helm
    layer: presentation
